"""Ode — Go emitter. Structured, concurrent, explicit."""

from typing import Any, Dict, List, Optional
from poetica.emitters.base import BaseEmitter


class GoEmitter(BaseEmitter):
    INDENT = "\t"
    COMMENT = "//"
    LANG = "go"

    def _header(self, ir) -> List[str]:
        lines = [f"// Generated by Poetica (target: go)", f'package main', f""]
        imports = ['"fmt"']
        ops = {op["op"] for op in ir.get("ops", [])}
        if "pack" in ops:
            imports.append('"encoding/json"')
        if "lift" in ops:
            imports.append('"os"')
        if len(imports) == 1:
            lines.append(f'import {imports[0]}')
        else:
            lines.append("import (")
            for imp in sorted(imports):
                lines.append(f"\t{imp}")
            lines.append(")")
        return lines

    def _fn_open(self, name: str) -> List[str]:
        safe = name.replace(':', '_').replace('-', '_').replace('.', '_')
        return [f"", f"func {safe}() {{"]

    def _fn_close(self, name: str) -> List[str]:
        return [f"}}"]

    def _fn_preamble(self, ir) -> List[str]:
        lines = []
        ops = {op["op"] for op in ir.get("ops", [])}
        if "remember" in ops:
            lines.append('_state := map[string]interface{}{}')
        return lines

    def _footer(self, ir) -> List[str]:
        name = ir.get("name", "program").replace(':', '_').replace('-', '_').replace('.', '_')
        return [f"", f"func main() {{", f"\t{name}()", f"}}"]

    def _block_close(self, block_type: str) -> Optional[str]:
        return "}"

    def _op_seed(self, op: Dict[str, Any]) -> str:
        return f"{op['name']} := {self._quote(op['value'])}"

    def _op_grow(self, op: Dict[str, Any]) -> str:
        return f"{op['name']} = append({op['name']}, {self._quote(op['source'])})"

    def _op_emit(self, op: Dict[str, Any]) -> str:
        if op.get('label'):
            return f'fmt.Printf("[{op["label"]}] %v\\n", {op["value"]})'
        return f"fmt.Println({self._quote(op['value'])})"

    def _op_pack(self, op: Dict[str, Any]) -> str:
        fmt = op['format']
        data = op['data']
        if fmt == 'json':
            return f"{data}JSON, _ := json.Marshal({data})"
        return f"{data}{fmt.title()} := fmt.Sprint({data})"

    def _op_lift(self, op: Dict[str, Any]) -> str:
        return f"os.WriteFile({self._quote(op['dest'])}, []byte(fmt.Sprint({op['name']})), 0644)"

    def _op_use(self, op: Dict[str, Any]) -> str:
        params = ", ".join(f"{self._quote(str(v))}" for v in op.get('params', {}).values())
        if params:
            return f"result := {op['tool']}({params})"
        return f"result := {op['tool']}()"

    def _op_when(self, op: Dict[str, Any]) -> str:
        return f"if {op['condition']} {{"

    def _op_when_in(self, op: Dict[str, Any]) -> str:
        return f"if contains({op['container']}, {op['subject']}) {{"

    def _op_if(self, op: Dict[str, Any]) -> str:
        return f"if {op['left']} == {op['right']} {{"

    def _op_else_when(self, op: Dict[str, Any]) -> str:
        return f"}} else if {op['condition']} {{"

    def _op_else(self, op: Dict[str, Any]) -> str:
        return "} else {"

    def _op_flow(self, op: Dict[str, Any]) -> str:
        return f"{op['dest']} := {op['source']}"

    def _op_bloom(self, op: Dict[str, Any]) -> str:
        return f"return {self._quote(op['value'])}"

    def _op_remember(self, op: Dict[str, Any]) -> str:
        return f'_state["{op["key"]}"] = {self._quote(op["value"])}'

    def _op_learn(self, op: Dict[str, Any]) -> str:
        return f'// learn pattern: {op["pattern"]}'

    def _op_for(self, op: Dict[str, Any]) -> str:
        return f"for _, {op['var']} := range {op['collection']} {{"
