"""Sonnet — Python emitter. Produces runnable Python."""

from typing import Any, Dict, List, Optional
from poetica.emitters.base import BaseEmitter


class PythonEmitter(BaseEmitter):
    INDENT = "    "
    COMMENT = "#"
    LANG = "python"

    def _header(self, ir) -> List[str]:
        lines = ["# Generated by Poetica (target: python)"]
        imports = self._needed_imports(ir)
        if imports:
            lines.append("")
            lines.extend(sorted(imports))
        return lines

    def _needed_imports(self, ir):
        imports = set()
        for op in ir.get("ops", []):
            if op["op"] == "pack":
                fmt = op.get("format", "")
                if fmt == "json":
                    imports.add("import json")
                elif fmt == "csv":
                    imports.add("import csv")
                    imports.add("import io")
            elif op["op"] == "lift":
                imports.add("import pathlib")
            elif op["op"] == "learn":
                imports.add("import re")
            elif op["op"] == "use":
                tool = op.get("tool", "")
                if "." in tool:
                    mod = tool.split(".")[0]
                    imports.add(f"import {mod}")
        return imports

    def _fn_open(self, name: str) -> List[str]:
        safe = name.replace(':', '_').replace('-', '_').replace('.', '_')
        return [f"", f"def {safe}():"]

    def _fn_close(self, name: str) -> List[str]:
        safe = name.replace(':', '_').replace('-', '_').replace('.', '_')
        return [f"", f"", f'if __name__ == "__main__":', f"    {safe}()"]

    def _fn_preamble(self, ir) -> List[str]:
        lines = []
        ops = {op["op"] for op in ir.get("ops", [])}
        if "remember" in ops:
            lines.append("_state = {}")
        if "learn" in ops:
            lines.append("_patterns = {}")
        return lines

    def _block_close(self, block_type: str) -> Optional[str]:
        return None  # Python uses indentation

    def _op_seed(self, op: Dict[str, Any]) -> str:
        return f"{op['name']} = {self._quote(op['value'])}"

    def _op_grow(self, op: Dict[str, Any]) -> str:
        return f"{op['name']}.append({self._quote(op['source'])})"

    def _op_emit(self, op: Dict[str, Any]) -> str:
        if op.get('label'):
            return f'print(f"[{op["label"]}] {{{op["value"]}}}")'
        return f"print({self._quote(op['value'])})"

    def _op_pack(self, op: Dict[str, Any]) -> str:
        fmt = op['format']
        data = op['data']
        if fmt == 'json':
            return f"{data}_json = json.dumps({data})"
        if fmt == 'csv':
            return f"{data}_csv = \"\\n\".join(\",\".join(str(c) for c in row) for row in {data})"
        return f"{data}_{fmt} = str({data})  # pack as {fmt}"

    def _op_lift(self, op: Dict[str, Any]) -> str:
        return f"pathlib.Path({self._quote(op['dest'])}).write_text(str({op['name']}))"

    def _op_use(self, op: Dict[str, Any]) -> str:
        params = ", ".join(f"{k}={self._quote(str(v))}" for k, v in op.get('params', {}).items())
        if params:
            return f"result = {op['tool']}({params})"
        return f"result = {op['tool']}()"

    def _op_when(self, op: Dict[str, Any]) -> str:
        return f"if {op['condition']}:"

    def _op_when_in(self, op: Dict[str, Any]) -> str:
        return f"if {op['subject']} in {op['container']}:"

    def _op_if(self, op: Dict[str, Any]) -> str:
        return f"if {op['left']} == {op['right']}:"

    def _op_else_when(self, op: Dict[str, Any]) -> str:
        return f"elif {op['condition']}:"

    def _op_else(self, op: Dict[str, Any]) -> str:
        return "else:"

    def _op_flow(self, op: Dict[str, Any]) -> str:
        return f"{op['dest']} = {op['source']}"

    def _op_bloom(self, op: Dict[str, Any]) -> str:
        return f"return {self._quote(op['value'])}"

    def _op_remember(self, op: Dict[str, Any]) -> str:
        return f'_state["{op["key"]}"] = {self._quote(op["value"])}'

    def _op_learn(self, op: Dict[str, Any]) -> str:
        return f'_patterns["{op["pattern"]}"] = re.compile(r"{op["pattern"]}")'

    def _op_for(self, op: Dict[str, Any]) -> str:
        return f"for {op['var']} in {op['collection']}:"
